name: ex_module_core
description: "A new Flutter package project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5

  dio: ^4.0.6
  multiple_localization:

  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  fluttertoast: ^8.2.5
  package_info_plus: ^7.0.0
  uuid: ^4.4.0
  device_info_plus: ^10.1.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  intl_utils: any
  freezed: ^2.5.2
  flutter_gen_runner: ^5.4.0
  connectivity_plus: ^6.0.2
  retrofit: ">=3.0.0 <4.0.0"
  json_annotation: ^4.6.0
  flutter_event_bus:
    git:
      url: https://github.com/AhmedNourJamalElDin/flutter_event_bus.git
      ref: master
  dartz: ^0.10.1
  event_bus: ^2.0.0
  flutter_localization: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  retrofit_generator: ">=4.0.0 <5.0.0"

# The following section is specific to Flutter.
flutter:
flutter_intl:
  enabled: true
  main_locale: vi
  class_name: ILanguage

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
